name: Build and test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'test'
            python: '3.11'
            os: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.3"

    - name: Setup Python
      run: uv python install ${{ matrix.python }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Unit tests
      run: uv run pytest tests

